# Generated by Django 3.1.5 on 2021-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('penerbit', models.CharField(max_length=50)),
                ('jumlah', models.IntegerField(null=True)),
            ],
        ),
    ]
