# Generated by Django 3.1.5 on 2021-01-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0003_auto_20210115_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='buku',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
